### ISSUE TITLE
Missing sample response

### ISSUE THREAD

**Issue by mtvbrianking** [sparkplug/mtn-momo-api-documentation#2]
Validate Account Holder request has not corresponding sample response.

https://mtn-momo-api-documentation.firebaseapp.com/use-cases/#validate-account-holder

I'm wondering what the response could be if,

1.  The account holder is registered and active
2. The account holder is not registered and, or is not active

The [other documentation](https://momodeveloper.mtn.com/docs/services/collection/operations/get-v1_0-accountholder-accountholderidtype-accountholderid-active) seems to be missing out this the 2nd response.

**Comment by raybesiga** [comment]
The other documentation is here: https://momodeveloper.mtn.com/api-documentation Go through it and let me know if it answers your query.

**Comment by mtvbrianking** [comment]
I managed to get the sample response after try and error.

But as you can see; the sample response is missing, hope that bit can be updated in the documentation.

![image](https://user-images.githubusercontent.com/5412360/63504952-4a9a0300-c4db-11e9-8456-e3d764997501.png)

https://momodeveloper.mtn.com/docs/services/collection/operations/get-v1_0-accountholder-accountholderidtype-accountholderid-active

**Comment by raybesiga** [comment]
Soon hopefully. Thank you for catching it.
